resources:
  limits:
    cpus: 1.0
    memory: 256

monitee_agent:
  docker_enable: true
  storage_monitoring_enable: true
  systemd_journald_enable: true

network:
  host_network: false
  https_port:
    bind_mode: published
    port_number: 8443
  http_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  config: /opt/tests/mnt/config
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
