app_version: latest
capabilities:
- description: Monitee-agent is able to use raw I/O.
  name: SYS_RAWIO
categories:
- monitoring
description: Monitee-agent is a android app based system monitoring tool.
home: https://github.com/Krillsson/monitee-agent
host_mounts:
- description: Required to read the OS release information.
  host_path: /etc/os-release
- description: Required to read information from disks.
  host_path: /dev
- description: Required to read disk device names.
  host_path: /run/udev
- description: Required to manage docker.
  host_path: /var/run/docker.sock
- description: Required to read journald logs.
  host_path: /etc/machine-id
- description: Required to read journald logs.
  host_path: /run/systemd/journal/socket
- description: Required to read journald logs.
  host_path: /run/log/journal
- description: Required to control systemd.
  host_path: /run/systemd
icon: https://media.sys.truenas.net/apps/monitee-agent/icons/icon.png
keywords:
- metric
- monitoring
lib_version: 2.1.16
lib_version_hash: dac15686f882b9ce65b8549a3d5c0ed7bafe2df7a9028880d1a99b0ff4af1eff
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: monitee-agent
run_as_context:
  - description: Monitee-agent runs as a non-root user.
    gid: 999
    group_name: monitee-agent
    uid: 999
    user_name: monitee-agent
screenshots:
- https://media.sys.truenas.net/apps/monitee-agent/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/krillsson/sys-api
title: Monitee-agent
train: community
version: 1.0.8
